### ISSUE TITLE
Validation fails despite explicitly allowing `electrum` in permissions

### ISSUE THREAD

**Issue by klochowicz** [runcitadel/app-cli#26]
I've tried validating the ItchySats app (https://github.com/runcitadel/apps/pull/44) and I noticed that if I take the suggestion I am given (rename `ELECTRUM_IP` to `APP_ELECTRUM_IP`) it fails with:

```
thread 'main' panicked at 'App is invalid: "Env var APP_ELECTRUM_IP not allowed by permissions"', src/bin/app-cli.rs:343:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`electrum` is specified in permissions section of the yml file.

**Comment by AaronDewes** [comment]
Then please ignore that deprecration message temporarily, I'll fix it later
